/**
 * Logros Page Component
 */

import { BottomNav } from '../components/BottomNav.js';
import { AppBackground } from '../components/AppBackground.js';

export default class LogrosPage {
    constructor() {
        this.name = 'logros';
    }

    render() {
        return `
      ${AppBackground()}
      <div class="app-container achievements-container">
        <!-- Content will be generated by Achievements.js -->
      </div>
      ${BottomNav('logros')}
    `;
    }

    async init() {
        // Dynamically import Achievements component
        const AchievementsModule = await import('../components/Achievements.js');
        const Achievements = AchievementsModule.default;
        Achievements.init();

        console.log('✅ Logros page initialized');
    }

    destroy() {
        // Cleanup if needed
    }
}
