/**
 * Mini Juego Page Component
 */

import { BottomNav } from '../components/BottomNav.js';
import { AppBackground } from '../components/AppBackground.js';

export default class MiniJuegoPage {
    constructor() {
        this.name = 'mini-juego';
    }

    render() {
        return `
      ${AppBackground()}
      <div class="app-container mini-game-container">
        <!-- Content will be generated by MiniGame.js -->
      </div>
      ${BottomNav('mini-juego')}
    `;
    }

    async init() {
        // Dynamically import MiniGame component
        const MiniGameModule = await import('../components/MiniGame.js');
        const MiniGame = MiniGameModule.default;
        MiniGame.init();

        console.log('✅ Mini Juego page initialized');
    }

    destroy() {
        // Cleanup if needed
    }
}
