/**
 * Perfil Page Component
 */

import { BottomNav } from '../components/BottomNav.js';
import { AppBackground } from '../components/AppBackground.js';

export default class PerfilPage {
    constructor() {
        this.name = 'perfil';
    }

    render() {
        return `
      ${AppBackground()}
      <div class="app-container profile-container">
        <!-- Content will be generated by Profile.js -->
      </div>
      ${BottomNav('perfil')}
    `;
    }

    async init() {
        // Dynamically import Profile component
        const ProfileModule = await import('../components/Profile.js');
        const Profile = ProfileModule.default;
        Profile.init();

        console.log('✅ Perfil page initialized');
    }

    destroy() {
        // Cleanup if needed
    }
}
