/**
 * Ranking Page Component
 */

import { BottomNav } from '../components/BottomNav.js';
import { AppBackground } from '../components/AppBackground.js';

export default class RankingPage {
    constructor() {
        this.name = 'ranking';
    }

    render() {
        return `
      ${AppBackground()}
      <div class="app-container ranking-container">
        <!-- Content will be generated by Ranking.js -->
      </div>
      ${BottomNav('ranking')}
    `;
    }

    async init() {
        // Dynamically import Ranking component
        const RankingModule = await import('../components/Ranking.js');
        const Ranking = RankingModule.default;
        Ranking.init();

        console.log('✅ Ranking page initialized');
    }

    destroy() {
        // Cleanup if needed
    }
}
