/**
 * Single Player Page Component
 */

import { AppBackground } from '../components/AppBackground.js';

export default class SinglePlayerPage {
    constructor() {
        this.name = 'single-player';
    }

    render() {
        return `
      ${AppBackground()}
      <div class="game-container">
        <!-- Game content will be generated by Game.js -->
        <header class="game-header">
          <button class="back-btn" onclick="window.history.back()">
            <i class="fas fa-arrow-left"></i>
          </button>
          <div class="game-info">
            <span class="game-mode">Modo Individual</span>
          </div>
          <div class="coins-display">
            <i class="fas fa-coins"></i>
            <span id="game-coins">0</span>
          </div>
        </header>
        
        <div id="game-content">
          <!-- Game UI will be injected here -->
        </div>
      </div>
    `;
    }

    async init() {
        // Dynamically import Game component
        const GameModule = await import('../components/Game.js');
        const Game = GameModule.default;
        Game.init();

        console.log('✅ Single Player page initialized');
    }

    destroy() {
        // Cleanup game state if needed
    }
}
